runtime: custom
env: flex
manual_scaling:
    instances: 1
resources:
    cpu: 1
    memory_gb: 4
    disk_size_gb: 20
network:
  forwarded_ports:
    - 80:8081
health_check:
  enable_health_check: False
